version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/simple-app/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Asia/Kolkata"
    labels:
      - "dependabot"
    assignees:
      - "thispsj"
    reviewers:
      - "thispsj"
    commit-message:
      prefix: "npm"
